# Site settings
encoding: utf-8
timezone: Europe/Berlin

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daniellimberger.de" # the base hostname & protocol for your site

title: Interactive Graphics Engineer
author: Daniel Limberger
email: daniel.limberger@hpi.de

description: > # this means to ignore newlines until "baseurl:"
    Berlin-based interactive graphics engineer and phd student in the Computer Graphics Systems group at the Hasso Plattner Institut, University of Potsdam.
subheading: > # this means to ignore newlines until "baseurl:"
    Berlin-based <span class="text-primary">interactive graphics engineer</span> and <span class="text-primary">phd student</span> in the Computer Graphics Systems group at the Hasso Plattner Institut, University of Potsdam.
# twitter_username: jekyllrb
github_username:  cgcostume

# Build settings
highlighter: false
markdown: kramdown
